import { ClientsType } from "@/models/clients";

const CLIENTS: ClientsType = [
  { id: "1", imgPath: "/neom.pngw3.webp" },
  { id: "2", imgPath: "/hyundai.pngw3.webp" },
  { id: "3", imgPath: "/pif.jpgw3.webp" },
  { id: "4", imgPath: "/hp.jpgw3.webp" },
  { id: "5", imgPath: "/bablas.jpgw3.webp" },
  { id: "6", imgPath: "/pixarprinting.jpgw3.webp" },
  { id: "7", imgPath: "/ktm.jpgw3.webp" },
  { id: "8", imgPath: "/feather down.pngw3.webp" },
  { id: "9", imgPath: "/race chip.pngw3.webp" },
  { id: "10", imgPath: "/gunbox.pngw3.webp" },
  { id: "11", imgPath: "/nvd.pngw3.webp" },
  { id: "12", imgPath: "/espn.pngw3.webp" },
  { id: "13", imgPath: "/labtest.pngw3.webp" },
  { id: "14", imgPath: "/es.pngw3.webp" },
  { id: "15", imgPath: "/daikin.pngw3.webp" },
  { id: "16", imgPath: "/ashrafs.pngw3.webp" },
  { id: "17", imgPath: "/kotak.pngw3.webp" },
  { id: "18", imgPath: "/tam.pngw3.webp" },
  { id: "19", imgPath: "/nova.pngw3.webp" },
  { id: "20", imgPath: "/yk.pngw3.webp" },
  { id: "21", imgPath: "/aljazira.pngw3.webp" },
  { id: "22", imgPath: "/kavalani.pngw3.webp" },
  { id: "23", imgPath: "/khalaifat.pngw3.webp" },
  { id: "24", imgPath: "/kawader.pngw3.webp" },
];
