import { ClientsType } from "@/models/clients";

export const CLIENTS: ClientsType = [
  { id: "1", imgName: "neom.pngw3.webp" },
  { id: "2", imgName: "hyundai.pngw3.webp" },
  { id: "3", imgName: "pif.jpgw3.webp" },
  { id: "4", imgName: "hp.jpgw3.webp" },
  { id: "5", imgName: "bablas.jpgw3.webp" },
  { id: "6", imgName: "pixarprinting.jpgw3.webp" },
  { id: "7", imgName: "ktm.jpgw3.webp" },
  { id: "8", imgName: "feather down.pngw3.webp" },
  { id: "9", imgName: "race chip.pngw3.webp" },
  { id: "10", imgName: "gunbox.pngw3.webp" },
  { id: "11", imgName: "nvd.pngw3.webp" },
  { id: "12", imgName: "espn.pngw3.webp" },
  { id: "13", imgName: "labtest.pngw3.webp" },
  { id: "14", imgName: "es.pngw3.webp" },
  { id: "15", imgName: "daikin.pngw3.webp" },
  { id: "16", imgName: "ashrafs.pngw3.webp" },
  { id: "17", imgName: "kotak.pngw3.webp" },
  { id: "18", imgName: "tam.pngw3.webp" },
  { id: "19", imgName: "nova.pngw3.webp" },
  { id: "20", imgName: "yk.pngw3.webp" },
  { id: "21", imgName: "aljazira.pngw3.webp" },
  { id: "22", imgName: "kavalani.pngw3.webp" },
  { id: "23", imgName: "khalaifat.pngw3.webp" },
  { id: "24", imgName: "kawader.pngw3.webp" },
];
